using WabbajackPreprocessor.Core.Analysis;
using WabbajackPreprocessor.Core.Mo2;
using WabbajackPreprocessor.Core.Settings;

namespace WabbajackPreprocessor.Core.Tests;

/// <summary>Builds a throwaway MO2 instance on disk and runs the full analysis over it.</summary>
public sealed class AnalyzerTests : IDisposable
{
    private readonly string _source;

    public AnalyzerTests()
    {
        _source = Directory.CreateTempSubdirectory("wjpp-instance-").FullName;

        // mods
        CreateMod("Alpha", "installationFile=Alpha-1234.7z");
        CreateMod("Beta", "installationFile=Beta-5678.7z");
        CreateMod("NoDownload", "installationFile=Vanished-999.7z");
        CreateMod("ByNexusIds", "installationFile=", "[installedFiles]", "size=1", "1\\modid=1234", "1\\fileid=111");
        CreateMod("HandMade", metaIni: null);
        CreateMod("Unlisted", "installationFile=");
        CreateMod("Optional AE", metaIni: null);
        CreateMod("Visuals_separator", "");

        // profile
        var profileDir = Path.Combine(_source, "profiles", "Main");
        Directory.CreateDirectory(profileDir);
        File.WriteAllText(Path.Combine(profileDir, "modlist.txt"),
            "# This file was automatically generated by Mod Organizer.\r\n" +
            "+Alpha\r\n" +
            "-Beta\r\n" +
            "+NoDownload\r\n" +
            "+ByNexusIds\r\n" +
            "+HandMade\r\n" +
            "-Optional AE\r\n" +
            "-Visuals_separator\r\n");

        // downloads: Alpha's archive with .meta (also carries the IDs ByNexusIds points at)
        var downloads = Path.Combine(_source, "downloads");
        Directory.CreateDirectory(downloads);
        File.WriteAllText(Path.Combine(downloads, "Alpha-1234.7z"), "x");
        File.WriteAllText(Path.Combine(downloads, "Alpha-1234.7z.meta"),
            "[General]\r\nmodID=1234\r\nfileID=111\r\n");
        File.WriteAllText(Path.Combine(downloads, "Orphan.7z"), "x"); // no .meta

        // an existing folder referenced by Ignore
        Directory.CreateDirectory(Path.Combine(_source, "logs"));
    }

    private void CreateMod(string name, params string[]? metaIni)
    {
        var dir = Path.Combine(_source, "mods", name);
        Directory.CreateDirectory(dir);
        if (metaIni is not null)
            File.WriteAllLines(Path.Combine(dir, "meta.ini"), ["[General]", .. metaIni]);
    }

    private CompilerSettings MakeSettings() => new()
    {
        Profile = "Main",
        Ignore = ["logs", "mods\\LongGoneMod"],
        AlwaysEnabled = ["mods\\Optional AE", "mods\\Alpha"],
        NoMatchInclude = ["mods\\HandMade", "mods\\handmade"],
        Include = [],
    };

    [Fact]
    public void Analyze_Finds_All_Three_Categories()
    {
        var instance = Mo2Instance.Load(_source);
        var result = Analyzer.Analyze(MakeSettings(), instance);

        Assert.Equal(["Main"], result.ProfilesUsed);

        // Stale: missing Ignore entry, duplicate NoMatchInclude entry, redundant AlwaysEnabled.
        Assert.Contains(result.StaleEntries, e =>
            e.List == TagList.Ignore && e.Entry == "mods\\LongGoneMod" && e.Kind == StaleEntryKind.Missing);
        Assert.Contains(result.StaleEntries, e =>
            e.List == TagList.NoMatchInclude && e.Index == 1 && e.Kind == StaleEntryKind.Duplicate);
        Assert.Contains(result.StaleEntries, e =>
            e.List == TagList.AlwaysEnabled && e.Entry == "mods\\Alpha" && e.Kind == StaleEntryKind.RedundantAlwaysEnabled);
        Assert.Equal(3, result.StaleEntries.Count);

        // Disabled: Beta (listed with '-') and Unlisted (absent from modlist.txt);
        // Optional AE is excluded because it is already AlwaysEnabled; the separator is skipped.
        Assert.Equal(2, result.DisabledMods.Count);
        Assert.Contains(result.DisabledMods, m => m.ModName == "Beta" && m.Note.Contains("Main"));
        Assert.Contains(result.DisabledMods, m => m.ModName == "Unlisted");

        // Without download: NoDownload (archive gone), Optional AE (AlwaysEnabled, no meta),
        // and HandMade (already tagged NoMatchInclude — listed with its current status).
        // Alpha links via installationFile, ByNexusIds via installedFiles IDs,
        // Beta is disabled (not compiled).
        Assert.Equal(3, result.ModsWithoutDownload.Count);
        Assert.Contains(result.ModsWithoutDownload, m =>
            m.ModName == "NoDownload" && m.Reason.Contains("Vanished-999.7z")
            && m is { TaggedInclude: false, TaggedNoMatchInclude: false });
        Assert.Contains(result.ModsWithoutDownload, m =>
            m.ModName == "Optional AE" && m.Reason.Contains("meta.ini"));
        Assert.Contains(result.ModsWithoutDownload, m =>
            m.ModName == "HandMade" && m is { TaggedInclude: false, TaggedNoMatchInclude: true });

        // Orphan.7z has no .meta -> warning.
        Assert.Contains(result.Warnings, w => w.Contains("no .meta"));
    }

    [Fact]
    public void Updater_Applies_Decisions_And_RoundTrips()
    {
        var settings = MakeSettings();
        var instance = Mo2Instance.Load(_source);
        var result = Analyzer.Analyze(settings, instance);

        var plan = new SettingsUpdatePlan();
        plan.RemoveEntries.AddRange(result.StaleEntries); // remove all three findings
        plan.MarkAlwaysEnabled.Add("Beta");
        plan.MarkNoMatchInclude.Add("NoDownload");
        plan.MarkInclude.Add("NoDownload"); // both tags on one path is legal in Wabbajack

        var changes = SettingsUpdater.Apply(settings, plan);
        Assert.Equal(6, changes.Count);

        Assert.Equal(["logs"], settings.Ignore);
        Assert.Equal(["mods\\HandMade"], settings.NoMatchInclude.Where(e => e.Contains("Hand")));
        Assert.Equal(["mods\\Optional AE", "mods\\Beta"], settings.AlwaysEnabled);
        Assert.Contains("mods\\NoDownload", settings.NoMatchInclude);
        Assert.Contains("mods\\NoDownload", settings.Include);

        // Re-adding an existing entry is a no-op.
        var again = new SettingsUpdatePlan();
        again.MarkAlwaysEnabled.Add("BETA");
        Assert.Empty(SettingsUpdater.Apply(settings, again));
    }

    [Fact]
    public void Updater_Untags_And_Retags_Mods()
    {
        var settings = MakeSettings(); // NoMatchInclude holds mods\HandMade twice (case dup)

        // Move HandMade from NoMatchInclude to Include.
        var plan = new SettingsUpdatePlan();
        plan.UntagNoMatchInclude.Add("HandMade");
        plan.MarkInclude.Add("HandMade");
        var changes = SettingsUpdater.Apply(settings, plan);

        Assert.Equal(2, changes.Count); // one removal (both case-dup entries), one add
        Assert.DoesNotContain(settings.NoMatchInclude, e => e.Contains("Hand", StringComparison.OrdinalIgnoreCase));
        Assert.Equal(["mods\\HandMade"], settings.Include);

        // Untagging a mod with no entry is a no-op.
        var again = new SettingsUpdatePlan();
        again.UntagNoMatchInclude.Add("HandMade");
        Assert.Empty(SettingsUpdater.Apply(settings, again));
    }

    public void Dispose() => Directory.Delete(_source, recursive: true);
}
