using WabbajackPreprocessor.Core;
using WabbajackPreprocessor.Core.Mo2;
using WabbajackPreprocessor.Core.Settings;

namespace WabbajackPreprocessor.Core.Tests;

public class RelPathsTests
{
    [Theory]
    [InlineData("mods\\Foo", "mods\\Foo", true)]
    [InlineData("mods\\Foo\\textures\\a.dds", "mods\\Foo", true)]
    [InlineData("mods/Foo/a.dds", "mods\\foo", true)]
    [InlineData("mods\\FooBar", "mods\\Foo", false)]
    [InlineData("mods", "mods\\Foo", false)]
    public void IsSameOrUnder_ComparesSegmentWise(string path, string folder, bool expected) =>
        Assert.Equal(expected, RelPaths.IsSameOrUnder(path, folder));

    [Fact]
    public void Normalize_UsesBackslashes()
    {
        Assert.Equal("mods\\Foo\\bar", RelPaths.Normalize("mods/Foo\\bar/"));
    }
}

public class IniFileTests
{
    [Fact]
    public void Parses_QSettings_Quirks()
    {
        var ini = IniFile.Parse("""
            [General]
            gameName=Skyrim Special Edition
            selected_profile=@ByteArray(My Profile)
            gamePath=@ByteArray(C:\\Steam\\steamapps\\common\\Skyrim Special Edition)
            installationFile=Some Mod-1234-1-0.7z
            dup=first
            dup=second
            color=@Variant(\0\0\0\x43...)
            key%20with%20space=x

            [installedFiles]
            size=1
            1\modid=1234
            1\fileid=56789

            [Settings]
            download_directory=D:/Modding/downloads
            """);

        Assert.Equal("My Profile", ini.Get("General", "selected_profile"));
        Assert.Equal(@"C:\Steam\steamapps\common\Skyrim Special Edition", ini.Get("General", "gamePath"));
        Assert.Equal("second", ini.Get("General", "dup"));
        Assert.StartsWith("@Variant(", ini.Get("General", "color"));
        Assert.Equal("x", ini.Get("General", "key with space"));
        Assert.Equal("1234", ini.Get("installedFiles", "1\\modid"));
        Assert.Equal("56789", ini.Get("installedFiles", "1\\fileid"));
        Assert.Equal("D:/Modding/downloads", ini.Get("Settings", "download_directory"));
        Assert.Null(ini.Get("General", "nope"));
        Assert.Null(ini.Get("Nope", "nope"));
    }
}

public class ModlistFileTests
{
    [Fact]
    public void Parses_Prefixes_And_Separators()
    {
        var entries = ModlistFile.Parse(new[]
        {
            "# This file was automatically generated by Mod Organizer.",
            "+Enabled Mod",
            "-Disabled Mod",
            "*DLC - Dawnguard.esm",
            "-Visuals_separator",
            "",
        });

        Assert.Equal(4, entries.Count);
        Assert.Equal(ModlistEntryKind.Enabled, entries[0].Kind);
        Assert.True(entries[0].WabbajackEnabled);
        Assert.Equal(ModlistEntryKind.Disabled, entries[1].Kind);
        Assert.False(entries[1].WabbajackEnabled);
        Assert.Equal(ModlistEntryKind.Foreign, entries[2].Kind);
        // MO2 writes separators with '-', but Wabbajack treats them as enabled.
        Assert.True(entries[3].IsSeparator);
        Assert.True(entries[3].WabbajackEnabled);
    }
}

public class CompilerSettingsFileTests
{
    private const string SampleJson = """
        {
          "ModlistIsNSFW": false,
          "Source": "P:\\Modding\\Modlists\\outlander",
          "Downloads": "P:\\Modding\\Modlists\\outlander\\downloads",
          "Game": "Morrowind",
          "OutputFile": "P:\\Modding\\Modlists\\Outlander.wabbajack",
          "MaxVerificationTime": "00:01:00",
          "ModListName": "Outlander",
          "Profile": "Outlander",
          "AdditionalProfiles": [],
          "NoMatchInclude": ["mods\\MMC Patches", "mods\\Ring\u0027s Patch Repo"],
          "Include": ["Outlander Keybinds.png"],
          "Ignore": [".git", "logs"],
          "AlwaysEnabled": ["mods\\Merged Grass"],
          "Version": "4.0.2",
          "Description": null,
          "SomeFutureProperty": {"nested": [1, 2]}
        }
        """;

    [Fact]
    public void RoundTrips_Including_Unknown_Properties()
    {
        var dir = Directory.CreateTempSubdirectory("wjpp-test-").FullName;
        try
        {
            var path = Path.Combine(dir, "Test.compiler_settings");
            File.WriteAllText(path, SampleJson);

            var settings = CompilerSettingsFile.Load(path);
            Assert.Equal("Morrowind", settings.Game);
            Assert.Equal("Outlander", settings.Profile);
            Assert.Equal(2, settings.NoMatchInclude.Count);
            Assert.Equal("mods\\Ring's Patch Repo", settings.NoMatchInclude[1]);
            Assert.Null(settings.Description);
            Assert.True(settings.ExtraProperties!.ContainsKey("SomeFutureProperty"));

            settings.AlwaysEnabled.Add("mods\\New Mod");
            var backupPath = CompilerSettingsFile.Save(path, settings);
            Assert.True(File.Exists(backupPath));
            Assert.Equal(SampleJson, File.ReadAllText(backupPath!));

            var reloaded = CompilerSettingsFile.Load(path);
            Assert.Equal(settings.NoMatchInclude, reloaded.NoMatchInclude);
            Assert.Contains("mods\\New Mod", reloaded.AlwaysEnabled);
            Assert.True(reloaded.ExtraProperties!.ContainsKey("SomeFutureProperty"));

            var written = File.ReadAllText(path);
            Assert.Contains("\"ModlistIsNSFW\"", written); // PascalCase, defaults written
            Assert.Contains("\"Description\": null", written); // nulls preserved
        }
        finally
        {
            Directory.Delete(dir, recursive: true);
        }
    }
}
